version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./compose/Dockerfile
      args:
        BUILD_MODE: dev
    command: make run-dev-docker
    environment:
      - MODE=dev
      - DJANGO_DEBUG=true
      - PYTHONUNBUFFERED=1
      - POSTGRES_DB=task_manager_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 8000:8000
    depends_on:
      - postgres

  postgres:
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_DB=task_manager_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_volume:
  static_volume:
  media_volume:
