# Generated by Django 4.1 on 2022-10-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="labels",
        ),
        migrations.AddField(
            model_name="task",
            name="label",
            field=models.ManyToManyField(
                related_name="labels", to="task_manager.label"
            ),
        ),
    ]
