# Generated by Django 4.1 on 2022-09-27 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "task_manager",
            "0002_alter_label_created_on_alter_status_created_on_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="siteuser",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
